# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import account_pb2 as account__pb2


class GreeterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SayHello = channel.unary_unary(
                '/helloworld.Greeter/SayHello',
                request_serializer=account__pb2.HelloRequest.SerializeToString,
                response_deserializer=account__pb2.HelloReply.FromString,
                )
        self.RunTerminalCommand = channel.unary_unary(
                '/helloworld.Greeter/RunTerminalCommand',
                request_serializer=account__pb2.HelloRequest.SerializeToString,
                response_deserializer=account__pb2.HelloReply.FromString,
                )
        self.RunTerminalCommand2 = channel.unary_unary(
                '/helloworld.Greeter/RunTerminalCommand2',
                request_serializer=account__pb2.HelloRequest.SerializeToString,
                response_deserializer=account__pb2.HelloReply.FromString,
                )
        self.RunTerminalCommand3 = channel.unary_unary(
                '/helloworld.Greeter/RunTerminalCommand3',
                request_serializer=account__pb2.HelloRequest.SerializeToString,
                response_deserializer=account__pb2.HelloReply.FromString,
                )


class GreeterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SayHello(self, request, context):
        """Sends a greeting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunTerminalCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunTerminalCommand2(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RunTerminalCommand3(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GreeterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SayHello': grpc.unary_unary_rpc_method_handler(
                    servicer.SayHello,
                    request_deserializer=account__pb2.HelloRequest.FromString,
                    response_serializer=account__pb2.HelloReply.SerializeToString,
            ),
            'RunTerminalCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.RunTerminalCommand,
                    request_deserializer=account__pb2.HelloRequest.FromString,
                    response_serializer=account__pb2.HelloReply.SerializeToString,
            ),
            'RunTerminalCommand2': grpc.unary_unary_rpc_method_handler(
                    servicer.RunTerminalCommand2,
                    request_deserializer=account__pb2.HelloRequest.FromString,
                    response_serializer=account__pb2.HelloReply.SerializeToString,
            ),
            'RunTerminalCommand3': grpc.unary_unary_rpc_method_handler(
                    servicer.RunTerminalCommand3,
                    request_deserializer=account__pb2.HelloRequest.FromString,
                    response_serializer=account__pb2.HelloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloworld.Greeter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Greeter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SayHello(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.Greeter/SayHello',
            account__pb2.HelloRequest.SerializeToString,
            account__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunTerminalCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.Greeter/RunTerminalCommand',
            account__pb2.HelloRequest.SerializeToString,
            account__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunTerminalCommand2(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.Greeter/RunTerminalCommand2',
            account__pb2.HelloRequest.SerializeToString,
            account__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RunTerminalCommand3(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloworld.Greeter/RunTerminalCommand3',
            account__pb2.HelloRequest.SerializeToString,
            account__pb2.HelloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
