# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='account.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\raccount.proto\"#\n\x11\x46ilesystemRequest\x12\x0e\n\x06\x66sPath\x18\x01 \x01(\t\"\"\n\x0f\x46ilesystemReply\x12\x0f\n\x07message\x18\x01 \x01(\t2=\n\x07Greeter\x12\x32\n\x08SayHello\x12\x12.FilesystemRequest\x1a\x10.FilesystemReply\"\x00\x62\x06proto3'
)




_FILESYSTEMREQUEST = _descriptor.Descriptor(
  name='FilesystemRequest',
  full_name='FilesystemRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fsPath', full_name='FilesystemRequest.fsPath', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=52,
)


_FILESYSTEMREPLY = _descriptor.Descriptor(
  name='FilesystemReply',
  full_name='FilesystemReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='FilesystemReply.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=88,
)

DESCRIPTOR.message_types_by_name['FilesystemRequest'] = _FILESYSTEMREQUEST
DESCRIPTOR.message_types_by_name['FilesystemReply'] = _FILESYSTEMREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FilesystemRequest = _reflection.GeneratedProtocolMessageType('FilesystemRequest', (_message.Message,), {
  'DESCRIPTOR' : _FILESYSTEMREQUEST,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:FilesystemRequest)
  })
_sym_db.RegisterMessage(FilesystemRequest)

FilesystemReply = _reflection.GeneratedProtocolMessageType('FilesystemReply', (_message.Message,), {
  'DESCRIPTOR' : _FILESYSTEMREPLY,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:FilesystemReply)
  })
_sym_db.RegisterMessage(FilesystemReply)



_GREETER = _descriptor.ServiceDescriptor(
  name='Greeter',
  full_name='Greeter',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=90,
  serialized_end=151,
  methods=[
  _descriptor.MethodDescriptor(
    name='SayHello',
    full_name='Greeter.SayHello',
    index=0,
    containing_service=None,
    input_type=_FILESYSTEMREQUEST,
    output_type=_FILESYSTEMREPLY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GREETER)

DESCRIPTOR.services_by_name['Greeter'] = _GREETER

# @@protoc_insertion_point(module_scope)
