# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: account.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='account.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\raccount.proto\"$\n\x08MountReq\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04path\x18\x02 \x01(\t\"\x17\n\x08MountRep\x12\x0b\n\x03msg\x18\x01 \x01(\t2(\n\x05Reply\x12\x1f\n\x05Mount\x12\t.MountReq\x1a\t.MountRep\"\x00\x62\x06proto3'
)




_MOUNTREQ = _descriptor.Descriptor(
  name='MountReq',
  full_name='MountReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='MountReq.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='path', full_name='MountReq.path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=53,
)


_MOUNTREP = _descriptor.Descriptor(
  name='MountRep',
  full_name='MountRep',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='MountRep.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=55,
  serialized_end=78,
)

DESCRIPTOR.message_types_by_name['MountReq'] = _MOUNTREQ
DESCRIPTOR.message_types_by_name['MountRep'] = _MOUNTREP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MountReq = _reflection.GeneratedProtocolMessageType('MountReq', (_message.Message,), {
  'DESCRIPTOR' : _MOUNTREQ,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:MountReq)
  })
_sym_db.RegisterMessage(MountReq)

MountRep = _reflection.GeneratedProtocolMessageType('MountRep', (_message.Message,), {
  'DESCRIPTOR' : _MOUNTREP,
  '__module__' : 'account_pb2'
  # @@protoc_insertion_point(class_scope:MountRep)
  })
_sym_db.RegisterMessage(MountRep)



_REPLY = _descriptor.ServiceDescriptor(
  name='Reply',
  full_name='Reply',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=80,
  serialized_end=120,
  methods=[
  _descriptor.MethodDescriptor(
    name='Mount',
    full_name='Reply.Mount',
    index=0,
    containing_service=None,
    input_type=_MOUNTREQ,
    output_type=_MOUNTREP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_REPLY)

DESCRIPTOR.services_by_name['Reply'] = _REPLY

# @@protoc_insertion_point(module_scope)
